### ISSUE TITLE
Update description and README with more detail

### ISSUE THREAD

**Issue by meiqimichelle** [18F/united#1]
Hey @thisisdano ! Thanks for your presentation today at the front end guild -- I think I see where you're going now with this.

I would recommend fleshing out the README and description with more details so others can know what this repo is about. In particular, I'd love to see:

- Sections for "What this is" and "What problem this solves" in the README
- A description and words in the README that indicate the maturity of the project. When I first clicked on the link, it felt like this was an '18F approved' framework, but after hearing you talk at the front end guild, I think you meant this more as an experiment. Perhaps label this as an 'experiment in prototyping utility classes' or similar?

**Comment by thisisdano** [comment]
Thanks, will do!
